app:
  environment: development
  monitor_port: 8080

exchange:
  name: binanceusdm
  markets:
    - BTC/USDT:USDT
    - ETH/USDT:USDT
    - SOL/USDT:USDT
    - DOGE/USDT:USDT
  api_key: ""
  api_secret: ""
  api_password: ""
  use_sandbox: false
  retry:
    max_attempts: 5
    min_delay: 500ms
    max_delay: 5s

trade_exchange:
  name: hyperliquid
  markets:
    - BTC/USDC:USDC
    - ETH/USDC:USDC
    - SOL/USDC:USDC
    - DOGE/USDC:USDC
  api_key: ""
  api_secret: ""
  api_password: ""
  use_sandbox: true
  wallet_address: ""
  private_key: ""

openai:
  api_key: "sk-fef11ff9ec234f1b8bdb57c4f0e91dfc"
  base_url: https://api.deepseek.com/v1
  model: deepseek-reasoner
  timeout: 180s

risk:
  max_trade_risk: 0.01
  max_daily_loss: 0.03
  max_exposure: 0.2
  confidence_full_risk: 0.8
  confidence_half_risk: 0.6
  daily_loss_reset_hour: 0
  enable_daily_stop_loss: true

execution:
  simulation: false
  slippage: 0.01
  time_in_force: GTC
  post_only: false

database:
  path: data/trades_ai.db
  max_open_conns: 4
  max_idle_conns: 4
  conn_max_lifetime: 1h
  in_memory: false

logging:
  level: info
  encoding: console
  development: true
  output_paths:
    - stdout
  error_output_paths:
    - stderr

scheduler:
  loop_interval: 3m
  decision_interval: 1h
  trend_interval: 4h
